[tool.poetry]
name = "edgegap-scheduling"
version = "1.1.0"
description = "The Edgegap Scheduling library includes various tools and helpers for helping with Scheduling Task. It is designed for use within the Edgegap organization."
authors = ["Bastien Roy <bastien@edgegap.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.7.1"
pytimeparse = "^1.1.8"
edgegap-logging = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
