[build-system]
requires = ["setuptools>=69.1.1", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src/"]
include = ["aett.postgres"]

[project]
name = "aett-postgres"
version = "1.0.0"
description = "Postgres connector for aett event store"
readme = "README.md"
authors = [{ name = "Jacob Reimers", email = "pypi@reimers.io" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["events", "event store", "postgres"]
dependencies = [
    'aett-domain >= 1.0.0',
    'psycopg-binary~=3.1.18'
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = ["pip-tools", "pytest", "behave"]

[project.urls]
Homepage = "https://github.com/jjrdk/aett"

[project.scripts]
