[tool.poetry]
name = "kkpyai"
version = "0.13.3"
description = "Utility over popular low-level AI API"
authors = ["Beinan Li <li.beinan@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
kkpyutil = "*"
matplotlib = "*"
mlxtend = "*"
scikit-learn = "*"
tensorflow = "*"
torch = "*"
torchinfo = "*"
torchmetrics = "*"
tqdm = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
coverage = "*"
pandas = "*"
requests = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
