[tool.poetry]
name = "echordlib"
version = "1.0.1"
description = "mandatory library for CHORD framework (image tratment, indexing and visualization)"
authors = ["Langlois Cyril, Gabriel L'Hôte, Clément Lafond, Joël Lachambre"]
license = "CeCILL"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
orix = "^0.11.1"
matplotlib = "^3.8.2"
pyqtgraph = "^0.13.3"
PyQt5 = "5.15.10"
PyQt5-Qt5 = "5.15.2"
tifffile = "^2023.12.9"
pyquaternion = "^0.9.9"
scikit-image = "^0.22.0"
scikit-learn = "^1.4.0"
h5py = "^3.10.0"
bm3d = "^4.0.1"
opencv-python = "^4.8.1.78"
cv = "^1.0.0"
largestinteriorrectangle = "^0.2.0"
cupy-cuda12x = "^13.0.0"
cuda-python="12.2.0"
tqdm = "^4.66.1"
ipywidgets = "^8.1.1"
joblib = "^1.3.2"
dill = "^0.3.8"

[[tool.poetry.source]]

name = "nvidia"
url = "https://pypi.nvidia.com/"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
