[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lightning_extensions"
version = "0.0.21"
authors = [
  { name="Edvards Zakovskis", email="edvards1999@gmail.com" },
]
description = "A small lightning extension package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/EdvardsZ/LightningExtensions"
"Bug Tracker" = "https://github.com/EdvardsZ/LightningExtensions/sampleproject/issues"