[tool.poetry]
# poetry version == 1.6
name = "svtter_template_creator"
version = "0.7.0"
readme = "README.md"
description = ""
authors = [ "svtter <svtter@163.com>",]
keywords = ["template", "django"]
include = ["src/*",]


[tool.poetry.group.dev.dependencies]
bumpversion = "^0.6.0"

[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

# [[tool.poetry.source]]
# name = "tsinghua"
# url = "https://pypi.tuna.tsinghua.edu.cn/simple"
# priority = "default"

[[tool.poetry.source]]
name = "aliyun"
url = "http://mirrors.aliyun.com/pypi/simple/"
priority = "default"

[[tool.poetry.source]]
name = "PyPI"
priority = "supplemental"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"
cookiecutter = "^2.1.1"
toml = "^0.10.2"
prompt-toolkit = "^3.0.43"
tomli = "^2.0.1"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
pytest-xdist = "^3.0.2"
pre-commit = "^2.20.0"

[tool.poetry.scripts]
tt = "svtter_template_creator.__main__:cli"

# [tool.pytest.ini_options]
# DJANGO_SETTINGS_MODULE = "conf.settings"
# python_files = "tests.py test_*.py *_tests.py"
# addopts = "-n3"
