[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "eprime_data"
authors = [{name = "Oliver Lindemann", email = "lindemann@essb.eur.nl"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
requires-python = ">=3.8"
dependencies =  []

[project.optional-dependencies]
pandas = ["pandas>=2.1"]

[project.scripts]
pyexam = "eprime_data.__main__:run"

[project.urls]
Home = "https://github.com/lindemann09/eprime-data"