[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[tool.hatch.build.targets.sdist]
include = [
  "rich_split",
  "tests",
  "LICENSE",
]

[project]
name = "rich_split"
version = "0.1.1"
authors = [
  { name="Danstiv", email="danstiv@yandex.ru" },
]
description = "Library for splitting simple strings and markdown"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Operating System :: OS Independent",
]
dependencies = [
    "marko>=2.0.3"
]

[project.urls]
"Homepage" = "https://github.com/Danstiv/rich_split"
"Bug Tracker" = "https://github.com/Danstiv/rich_split/issues"
