[tool.poetry]
name = "strideutils"
version = "0.2.9"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9"
google-api-python-client = ">=2.100.0"
google-auth-httplib2 = ">=0.1.1"
google-auth-oauthlib = ">=1.1.0"
google-cloud-bigquery = ">=3.11.4"
gspread = ">=6.0.2"
pytz = ">=2023.3"
redis = ">=4.5.4"
bech32 = ">=1.2.0"
tqdm = ">=4.66.1"
slack-sdk = ">=3.23.0"
pandas = ">=2.1.1"
twilio = ">=8.10.0"
tabulate = ">=0.9.0"
pyyaml = ">=6.0.1"
python-dateutil = ">=2.8.2"
pycryptodome = ">=3.20.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
