[project]
name = "smtp-proxy"
version = "0.1.2"
description = "SMTP server meant to redirect SMTP requests to a third-party email provider"
readme = "README.md"
requires-python = ">=3"
keywords = ["smtp", "email", "proxy"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
]

dependencies = [
  "aiosmtpd",
  "click",
  #"azure-identity",
  #"msgrasph-sdk",
  "sendgrid",
  "sendgrid-async",
]

[project.optional-dependencies]
dev = ["pytest", "pytest-asyncio"]

# The following would provide a command line executable called `sample`
# which executes the function `main` from this package when invoked.
[project.scripts]
smtp-proxy = "smtp_proxy.smtp_proxy:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
pythonpath = ["src"]