[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pathlib_next"
version = "0.1.0"
authors = [{ name = "Jose A" }]
description = "Generic Path Protocol based pathlib"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = []
[project.optional-dependencies]
uri = ["uritools"]
http = ["requests", "pathlib_next[uri]"]
sftp = ["paramiko", "pathlib_next[uri]"]


[project.urls]
Homepage = "https://github.com/jose-pr/pathlib_next/"
Issues = "https://github.com/jose-pr/pathlib_next/issues"

[tool.hatch.build.targets.sdist]
exclude = ["/.*"]
